name: ubuntu-faster-whisper

services:
  faster-whisper:
    image: radu103/ubuntu-faster-whisper:latest
    volumes:
      - faster_whisper_data:/app/audio
      - faster_whisper_models:/root/.cache
      - faster_whisper_output:/app/output
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - WHISPER_MODEL=large-v3-turbo
      - WHISPER_BEAM=10               #optional, default is 5
      - WHISPER_LANG=ro               #optional
      # PostgreSQL settings (optional - comment out if not using PostgreSQL)
      - POSTGRES_HOST=172.100.0.2
      - POSTGRES_PORT=5432
      - POSTGRES_DB=whisper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "10301:10301"
    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]    # Keep the container running
    stdin_open: true
    tty: true
    # Link to postgres service if using PostgreSQL
    depends_on:
      - postgres

  # PostgreSQL database service (optional)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.100.0.2

  pgadmin4:
    depends_on:
      - postgres
    image: dpage/pgadmin4:9.3.0
    ports:
      - 54321:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin4.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    restart: unless-stopped

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24

volumes:
  faster_whisper_data:
    driver: local
    driver_opts:
      type: none
      device: R:/ubuntu-faster-whisper/audio
      o: bind
  faster_whisper_models:
    driver: local
    driver_opts:
      type: none
      device: R:/ubuntu-faster-whisper/models
      o: bind
  faster_whisper_output:
    driver: local
    driver_opts:
      type: none
      device: R:/ubuntu-faster-whisper/output
      o: bind
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: R:/ubuntu-faster-whisper/postgres_data
      o: bind
  pgadmin4_data:
    driver: local
    driver_opts:
      type: none
      device: R:/ubuntu-faster-whisper/pgadmin4_data
      o: bind